package main

import "testing"

func Test_parseAndFormatMessage(t *testing.T) {
	type args struct {
		message string
	}
	tests := []struct {
		name string
		args args
		want string
	}{
		{"JOIN", args{message: "2022-02-01 15:31:19 [JOIN] Mattie joined the game"}, ":green_circle: | `Mattie` joined the game!"},
		{"LEAVE", args{message: "2022-02-01 15:31:30 [LEAVE] Mattie left the game"}, ":red_circle: | `Mattie` left the game!"},
		{"CHAT", args{message: "2022-02-01 15:31:30 [CHAT] Mattie: Some chat message"}, ":speech_left: | `Mattie`: Some chat message"},
		// Messages below are generated by the companion mod, but I still want them to go through the normal flow!
		{"PLAYER_DIED", args{message: "[FactoriGOChatBot]: \"2852569 [PLAYER_DIED:Mattie]\""}, ":skull: | Player died: `Mattie`"},
		{"RESEARCH_STARTED", args{message: "[FactoriGOChatBot]: \"3045105 [RESEARCH_STARTED:nuclear-power]\""}, ":microscope: | Research started: `nuclear-power`"},
		{"RESEARCH_FINISHED", args{message: "[FactoriGOChatBot]: \"3229214 [RESEARCH_FINISHED:nuclear-power]\""}, ":microscope: | Research finished: `nuclear-power`"},
		// Corrupted messages (as I don't know yet how to fix the file read, so it will have a single line guaranteed
		{"CORRUPT", args{message: "[FactoriGOChatBot]: \"2852569 [foobar]\""}, ""},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			if got := parseAndFormatMessage(tt.args.message); got != tt.want {
				t.Errorf("parseAndFormatMessage() = %v, want %v", got, tt.want)
			}
		})
	}
}
